# Legacy Token introspection API
# Version: Draft
openapi: 3.0.0
info:
  title: Revocation API
  description: |
    The revocation endpoints revoke refresh tokens and access tokens. The API is public, the
    client_id post parameter MUST be a valid client ID and match the client ID used to request the
    token.
  version: '1.0.0'
servers:
  - url: https://{capture-domain}.{region}.janraincapture.com/access
    variables:
      capture-domain:
        description: The customer's capture domain.
        default: janrain-test
      region:
        description: The region the domain is deployed in.
        default: us
paths:
  /revokeAccessToken:
    post:
      summary: Revoke Access Token.
      description: >
        The Revoke Access Token endpoint invalidates an access token. When the access token is revoked,
        any refresh tokens will also be revoked.
      operationId: revokeAccessToken
      tags:
        - Revocation
      requestBody:
        required: true
        content:
          application/xxx-form-url-encoded:
            schema:
              $ref: '#components/schemas/TokenRequest'
      responses:
        200:
          description: >
            HTTP status code 200 is returned if the access token was revoked successfully.
        400:
          description: >
            Bad request
            * Invalid_request: missing required token parameter or token invalid.
            * Invalid_request: missing required client_id parameter.
        401:
          description: >
            Invalid credentials
            * The client_id does not match the client_id associated with the token.
        429:
          description: >
            Too may requests. Returned when an invalid token is passed and the circuit breaker logic has tripped.
            See https://docs.google.com/document/d/1SaxTCZWZ1qDsDB81PBeN99YnBK1iAqsuG_BRkqRpCQY/edit#
  /revokeRefreshToken:
    post:
      summary: Revoke Refresh Token
      description: >
        The Revoke Refresh Token endpoint invalidates a refresh token. When the refresh token is revoked,
        any access tokens will also be revoked.
      operationId: revokeRefreshToken
      tags:
        - Revocation
      requestBody:
        required: true
        content:
          application/xxx-form-url-encoded:
            schema:
              $ref: '#components/schemas/TokenRequest'
      responses:
        200:
          description: >
            HTTP status code 200 is returned if the refresh token was revoked successfully.
        400:
          description: >
            Bad request
            * Invalid_request: missing required token parameter or token invalid.
            * Invalid_request: missing required client_id parameter.
        401:
          description: >
            Invalid credentials
            * The client_id does match the client_id associated with the token.
        429:
          description: >
            Too may requests. Returned when an invalid token is passed and the circuit breaker logic has tripped.
            See https://docs.google.com/document/d/1SaxTCZWZ1qDsDB81PBeN99YnBK1iAqsuG_BRkqRpCQY/edit#
components:
  schemas:
    TokenRequest:
      type: object
      properties:
        client_id:
          type: string
        token:
          type: string
      required:
        - client_id
        - token