# Task Master API
# Version: 0.0.1
openapi: 3.0.0
info:
  title: Task Manager API
  description: |
    API to manage objects in the task manager system.
  version: '0.0.1'
servers:
  - url: https://tasks.rogerbixby.com/{version}
    variables:
      version:
        description: The API version
        default: v1
paths:
  /projects:
    get:
      summary: Get Projects
      description: >
        The Get Projects endpint returns a list of Projects.
      operationId: getProjects
      tags:
        - Projects
      responses:
        200:
          description: >
